2018-06-14 17:47:41,851 [Thread-2:10604] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Myblog\Myblog\x_blog\views.py", line 16, in blog
    return render(request, 'x_blog/blog.html', locals())
  File "D:\Python36\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python36\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python36\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36\lib\site-packages\django\template\defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Python36\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 911, in _resolve_lookup
    current = current()
  File "D:\Myblog\Myblog\x_blog\models.py", line 62, in increase_like
    self.like += 1
AttributeError: 'Post' object has no attribute 'like'
2018-06-14 17:49:13,578 [Thread-2:6908] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Myblog\Myblog\x_blog\views.py", line 16, in blog
    return render(request, 'x_blog/blog.html', locals())
  File "D:\Python36\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python36\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "D:\Python36\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36\lib\site-packages\django\template\defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Python36\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "D:\Python36\lib\site-packages\django\template\base.py", line 911, in _resolve_lookup
    current = current()
  File "D:\Myblog\Myblog\x_blog\models.py", line 62, in increase_like
    self.like += 1
AttributeError: 'Post' object has no attribute 'like'
